feature_config:
        mag: standard
        dip: min_max
        rake: min_max
        rrup: standard
        rrup_ln: ln
        vs30: standard

        active_shallow: null
        volcanic: null
        is_point_source: null

im_config:
#        PGV: standard
#        PGA: standard
#        pSA_0.01: standard
#        pSA_0.02: standard
#        pSA_0.03: standard
#        pSA_0.04: standard
#        pSA_0.05: standard
#        pSA_0.075: standard
#        pSA_0.1: standard
#        pSA_0.12: standard
#        pSA_0.15: standard
#        pSA_0.17: standard
#        pSA_0.2: standard
#        pSA_0.25: standard
#        pSA_0.3: standard
#        pSA_0.4: standard
#        pSA_0.5: standard
#        pSA_0.6: standard
#        pSA_0.7: standard
#        pSA_0.75: standard
#        pSA_0.8: standard
#        pSA_0.9: standard
#        pSA_1.0: standard
#        pSA_1.25: standard
#        pSA_1.5: standard
#        pSA_2.0: standard
#        pSA_2.5: standard
#        pSA_3.0: standard
#        pSA_4.0: standard
#        pSA_5.0: standard
#        pSA_6.0: standard
#        pSA_7.5: standard
#        pSA_10.0: standard

        PGV: standard
        PGA: standard
        pSA_0.25: standard
        pSA_0.5: standard
        pSA_1.0: standard
        pSA_3.0: standard
        pSA_5.0: standard
        pSA_10.0: standard
