seed: 42

rel_imdb_ffp: nn_gmm/20250606_CS200m_imdb.db
rel_test_events_ffp: nn_gmm/test_events.npy
max_rrup: 300
ignore_events: null

im_set: pSA
scale_ims: False

site_inputs: 
- nztm_x
- nztm_y 
# - lat
# - lon
- vs30
- z1p0
# - z2p5

source_inputs:
- "magnitude"
- "tect_type"
# - "rake" 
# - "dip"
# - "dtop"
# - "dbottom"
# - "hypo_depth"
# - "hypo_lat"
# - "hypo_lon"

source_to_site_inputs:
- "rrup"
- "rjb"
- "rx"
# - "ry"


# Sample weighting
apply_mag_sample_weighting: True
max_mag_weight: 2.5
apply_rrup_sample_weighting: True
max_rrup_weight: 2.5
apply_vs30_sample_weighting: True
max_vs30_weight: 2.5
total_max_weight: 5.0

n_epochs: 100
batch_size: 1024


model:
  units: [32, 32, 64]
  use_batch_norm: True
  activation: relu
  l2_reg: 0.0001


rel_results_dir: nn_gmm/results
