rel_base_output_dir: nn_gmm/hp_opt

n_event_folds: 2
n_site_folds: 2
n_epochs: 5


batch_sizes: [128, 256, 512, 1024, 2048, 4096]
learning_rates: [0.01, 0.005, 0.001, 0.0005, 0.0001]
n_layers_min: 1
n_layers_max: 5
unit_sizes: [16, 32, 64, 128]
activation_fns: [relu, leaky_relu, elu]
l2_regs: [0.01, 0.005, 0.001, 0.0005, 0.0001]
dropout_rates: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]