type: "mag"
fixed_inputs:
    vs30: 500
    z1p0: 0.1
    z2p5: 1
    tect_type: "ACTIVE_SHALLOW"
    rake: 10
    dip: 60
    dtop: 0
    dbottom: 15
    hypo_depth: 8.5
    rrup: 75
    rjb: 75
    rx: 75
    ry: 75
records_range:
    vs30: 25
    rrup: 5
    rjb: 5
    rx: 7.5
    ry: 7.5