type: "mag"
min_mag: 5.0
max_mag: 7.75
fixed_inputs:
    vs30: 500
    z1p0: 0.1
    z2p5: 1
    tect_type: "ACTIVE_SHALLOW"
    rake: 10
    dip: 60
    dtop: 0
    dbottom: 15
    hypo_depth: 8.5
    is_point_source: False
    rrup: 120
    rjb: 120
    rx: 120
    ry: 120
records_range:
    vs30: 30
    rrup: 5
    rjb: 5
    rx: 10
    ry: 10