type: "mag"
min_mag: 5.0
max_mag: 7.25
fixed_inputs:
    vs30: 500
    z1p0: 0.1
    z2p5: 1
    tect_type: "SUBDUCTION_SLAB"
    rake: -90
    dip: 45
    dtop: 50
    dbottom: 50
    hypo_depth: 20
    is_point_source: True
    rrup: 30
    rjb: 30
    rx: 30
    ry: 30
records_range:
    vs30: 30
    rrup: 2.5
    hypo_depth: 10
