rel_base_model_dir: null

loc_inputs:
  - "nztm_x"
  - "nztm_y"

rel_pre_loc_emb_model_dir: nn_gmm/results/loc_models/0929_1130_optimized_siteCond_25Epochs
loc_emb_dim: null
loc_emb_model_config: null

adj_model_config:
  units: [64]
  activation: "leaky_relu"
  use_batch_norm: False
  dropout_rate: 0.0
  l2_reg: 0.0005

n_epochs: 25
batch_size: 512
adj_learning_rate: 0.001
loc_learning_rate: 0.0001

loc_emb_max_grad_norm: null
adj_max_grad_norm: null

rel_results_dir: nn_gmm/results
