seed: 42

rel_imdb_ffp: "nn_gmm/202505_CS200m_imdb.db"

ignore_events: null

site_inputs: 
- "lat"
- "lon"
- "vs30"
- "z1p0"
- "z2p5"

source_inputs:
- "magnitude"
- "tect_type"
- "rake"
- "dip"
- "dtop"
- "dbottom"
# - "hypo_depth"
# - "hypo_lat"
# - "hypo_lon"

source_to_site_inputs:
- "rrup"
- "rjb"
- "rx"
# - "ry"




