feature_config:
        dip: min_max
        rake: min_max
        mag: standard
        vs30: standard
        z1p0: standard
        z2p5: standard
        vs500: standard
        rrup: standard
        rx: standard
        rjb: standard
        ry: standard
        active_shallow: null
        volcanic: null
im_config:
  #        PGV: standard
        PGA: standard
        pSA_0.05: standard
        pSA_0.1: standard
        pSA_0.25: standard
        pSA_0.5: standard
        pSA_1.0: standard
        pSA_2.0: standard
        pSA_3.0: standard
        pSA_5.0: standard
        pSA_10.0: standard
