hidden_layer_func: relu
l2: 0.05
#l2: null
dropout: null

n_pre_layers: 3
n_pre_units: 8

n_core_layers: 2
n_core_units: 16

n_out_units: 16
n_out_layers: 1

batch_size: 4096
shuffle_buffer_size: 5000000
n_epochs: 100

optimizer: adam
learning_rate: 0.001
learning_rate_patience: null
learning_rate_factor: null

loss_key: huber
delta: 1.0
cache: True
