#hidden_layer_func: relu
hidden_layer_func: elu
#hidden_layer_func: selu
#hidden_layer_func: tanh
#l2: 0.1
l2: null
dropout: 0.1
#dropout: null

n_units: 256
n_layers: 4

n_out_units: 32
n_out_layers: 1

#batch_size: 5120
#batch_size: 4096
batch_size: 8192
#batch_size: 16384
#batch_size: 1024
shuffle_buffer_size: 5000000
n_epochs: 100

optimizer: adam
learning_rate: 0.001
learning_rate_patience: null
learning_rate_factor: null

loss_key: huber
delta: 1.0
cache: True
