    train_data_dir: /home/cbs51/dev/work/data/nn_gmm/training_data
    base_output_dir: /home/cbs51/dev/work/data/nn_gmm/results/test
    basin_dir: /home/cbs51/dev/work/data/nn_gmm/input_data/site_data/basin_stations